SHELL := /bin/bash

.PHONY: all build clean getimg

FNAME = tsne

all: build

getimg:
	@echo TODO

build:
	pdflatex $(FNAME).tex

clean:
	rm -f *.{log,aux,nav,out,snm,toc,blg,bbl,fdb_latexmk,fls,synctex.gz,zip,pdfsync}


