#!/bin/bash

# Maximum number of cores to use
MAX_CORES=6

# AWS Bucket to store results
AWS_BUCKET="s3://cytof-cb-results/cb-preprocessed/"

# STAGGER_TIME in seconds. To avoid mass dumping to disk simultaneously. 
STAGGER_TIME=100

# Experiment settings
MCMC_ITER=1000
BURN=20000
K_MCMC=20
L_MCMC=5
betaPriorScales="0.01 1 10"
betaTunerInit="0.01 0.1"
RESULTS_DIR="results/cb_preprocessed/"
SEED=0

if [[ $@ == **--test** ]]
then
    echo "Testing with small numbers..."
    # STAGGER_TIME in seconds. To avoid mass dumping to disk simultaneously. 
    STAGGER_TIME=0

    # Experiment settings
    MCMC_ITER=100
    BURN=100
    K_MCMC=10
    L_MCMC=5
fi

# simulation number, just for book keeping. Ignore this.
simNumber=0


for scale in $betaPriorScales; do
  for bti in $betaTunerInit; do
    # Simulation number
    simNumber=$((simNumber + 1)) 

    # Experiment name
    exp_name="K_MCMC${K_MCMC}_L_MCMC${L_MCMC}_scale${scale}_tuner${bti}_SEED${SEED}"

    # Output directory
    outdir="$RESULTS_DIR/$exp_name/"
    mkdir -p $outdir

    # Julia Command to run
    jlCmd="julia cb.jl --K_MCMC=${K_MCMC} --L_MCMC=${L_MCMC} --b0PriorSd=${scale} --b1PriorScale=${scale} --SEED=${SEED} --RESULTS_DIR=$RESULTS_DIR --EXP_NAME=$exp_name --MCMC_ITER=$MCMC_ITER --BURN=$BURN --b0TunerInit=${bti} --b1TunerInit=${bti}"

    # Sync results to S3
    syncToS3="aws s3 sync $outdir $AWS_BUCKET/$exp_name --exclude '*.nfs*'"

    # Remove output files to save space on cluster
    rmOutput="rm -rf ${outdir}"

    cmd="$jlCmd > ${outdir}/log.txt && $syncToS3 && $rmOutput"

    sem -j $MAX_CORES $cmd
    echo $cmd

    echo "Results for simulation $simNumber -> $outdir"

    sleep $STAGGER_TIME
  done
done
